{ "height":10,
 "layers":[
        {
         "data":[7, 8, 7, 8, 7, 7, 7, 8, 7, 7, 7, 8, 7, 8, 7, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 6, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 6, 6, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 6, 6, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 6, 6, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 6, 6, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 6, 6, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 6, 6, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 10, 9, 6, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5],
         "height":10,
         "name":"field",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"Collisions",
         "objects":[
                {
                 "height":0,
                 "id":12,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":1,
                         "y":576
                        }, 
                        {
                         "x":832,
                         "y":577
                        }, 
                        {
                         "x":832,
                         "y":1
                        }, 
                        {
                         "x":896,
                         "y":1
                        }, 
                        {
                         "x":896,
                         "y":641
                        }, 
                        {
                         "x":-64,
                         "y":641
                        }, 
                        {
                         "x":-64,
                         "y":1
                        }, 
                        {
                         "x":0,
                         "y":1
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":64,
                 "y":-1
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"spawn",
         "objects":[
                {
                 "gid":19,
                 "height":64,
                 "id":2,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":93,
                 "y":547
                }, 
                {
                 "gid":19,
                 "height":64,
                 "id":4,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":101,
                 "y":362
                }, 
                {
                 "gid":19,
                 "height":64,
                 "id":5,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":162,
                 "y":401
                }, 
                {
                 "gid":19,
                 "height":64,
                 "id":6,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":67,
                 "y":544
                }, 
                {
                 "gid":19,
                 "height":64,
                 "id":7,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":67,
                 "y":544
                }, 
                {
                 "gid":11,
                 "height":64,
                 "id":10,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":151,
                 "y":502
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextobjectid":13,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.0.3",
 "tileheight":64,
 "tilesets":[
        {
         "columns":5,
         "firstgid":1,
         "image":"tileset.png",
         "imageheight":384,
         "imagewidth":320,
         "margin":0,
         "name":"tileset",
         "spacing":0,
         "tilecount":30,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "type":"map",
 "version":1,
 "width":15
}